config:
  debug_mode: True
  debugGaussian: True
  debugThreshold: True
  debugDilateErode: False
  debug_dilate: True
  debug_erode: True
  debug_crossed_blobs: True
  debug_all_current_blobs: True

videos:
  video_1:
    id: 1
    max_track_frames: 10
    case: 1
    linePoint1:
      x: 0
      y: 96
    linePoint2:
      x: 319
      y: 96
    filepath: videos/SYS_Memorial_Hal_normal_320x240.avi
    blob:
      area: 400
      min_aspect_ratio: 0.3
      max_aspect_ratio: 4.0
      width: 20
      height: 20
      diagonal_size: 70.0
      contour_area_by_area: 0.5
    threshold_value: 25
    gaussian_kernel: 9
    kernel_dilate1: 3
    kernel_erode1: 5
    kernel_dilate2: 5
    kernel_erode2: 3
    source: ""
  video_2:
    id: 2
    max_track_frames: 15
    case: 1
    linePoint1:
      x: 0
      y: 96
    linePoint2:
      x: 319
      y: 96
    filepath: videos/Flora_Exposition_normal_320x240.avi
    blob:
      area: 400
      min_aspect_ratio: 0.2
      max_aspect_ratio: 4.2
      width: 30
      height: 30
      diagonal_size: 60.0
      contour_area_by_area: 0.5
    threshold_value: 15
    gaussian_kernel: 5
    kernel_dilate1: 5
    kernel_erode1: 3
    kernel_dilate2: 5
    kernel_erode2: 5
    source: ""
  video_3:
    id: 3
    max_track_frames: 18
    case: 1
    linePoint1:
      x: 5
      y: 240
    linePoint2:
      x: 350
      y: 240
    filepath: videos/main-st-sag-habor-ny-20180402.mp4
    blob:
      area: 4000
      min_aspect_ratio: 0.2
      max_aspect_ratio: 2.2
      width: 50
      height: 90
      diagonal_size: 80.0
      contour_area_by_area: 0.5
    threshold_value: 15
    gaussian_kernel: 9
    kernel_dilate1: 9
    kernel_erode1: 5
    kernel_dilate2: 5
    kernel_erode2: 3
    source: https://www.youtube.com/watch?v=KVcW9O7eRTQ
