config:
  debug_mode: True
  debugGaussian: False
  debugThreshold: True
  debugDilateErode: False
  debug_dilate: True
  debug_erode: True
  debug_crossed_blobs: True
  debug_all_current_blobs: True

videos:
  video_1:
    id: 1
    max_track_frames: 10
    case: 1
    linePoint1:
      x: 0
      y: 96
    linePoint2:
      x: 319
      y: 96
    filepath: videos/SYS_Memorial_Hal_normal_320x240.avi
    blob:
      area: 400
      min_aspect_ratio: 0.3
      max_aspect_ratio: 4.0
      width: 20
      height: 20
      diagonal_size: 70.0
      contour_area_by_area: 0.5
    threshold_value: 25
    gaussian_kernel: 9
    kernel_dilate1: 3
    kernel_erode1: 5
    kernel_dilate2: 5
    kernel_erode2: 3
  video_2:
    id: 2
    max_track_frames: 15
    case: 1
    linePoint1:
      x: 0
      y: 96
    linePoint2:
      x: 319
      y: 96
    filepath: videos/Flora_Exposition_normal_320x240.avi
    blob:
      area: 400
      min_aspect_ratio: 0.2
      max_aspect_ratio: 4.2
      width: 30
      height: 30
      diagonal_size: 60.0
      contour_area_by_area: 0.5
    threshold_value: 15
    gaussian_kernel: 5
    kernel_dilate1: 5
    kernel_erode1: 3
    kernel_dilate2: 5
    kernel_erode2: 5
  video_3:
    id: 3
    case: 1
    linePoint1:
      x: 0
      y: 96
    linePoint2:
      x: 319
      y: 96
    filepath: videos/SYS_Memorial_Hal_normal_320x240.avi
    blob:
      area: 400
      min_aspect_ratio: 0.2
      max_aspect_ratio: 4.2
      width: 30
      height: 30
      diagonal_size: 60.0
      contour_area_by_area: 0.5
    kernel_erode1: 3x3
    times_erode1: 1
    kernel_dilate1: 5x5
    times_dilate1: 2
    kernel_erode2: 15x15
    times_erode1: 1
    kernel_dilate2: 15x15
    times_dilate2: 1
